# Generated by Django 5.0.4 on 2024-11-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_apartmentsearch_prediction_quartal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='valuation_tokens',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='apartmentsearch',
            name='prediction_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=11),
        ),
    ]
