# Generated by Django 5.0.4 on 2024-06-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('floor', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.IntegerField()),
                ('sq', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
                ('price_per_sq', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
