# Generated by Django 5.0.4 on 2024-07-03 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='update_date',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
        ),
    ]
