# Generated by Django 5.0.4 on 2024-07-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0003_alter_apartment_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='offer_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
